const UPDATE_INPUT_START_VALUE = 'UPDATE_INPUT_START_VALUE';
const ON_CHANGE_INPUT_START = 'ON_CHANGE_INPUT_START';
const RECEIVED_DATA_ON_CHANGE_INPUT_START = 'RECEIVED_DATA_ON_CHANGE_INPUT_START';
const ON_CHANGE_INPUT_ARRIVED = 'ON_CHANGE_INPUT_ARRIVED';
const RECEIVED_DATA_ON_CHANGE_INPUT_ARRIVED = 'RECEIVED_DATA_ON_CHANGE_INPUT_ARRIVED';
const FOCUS_INPUT_START = 'FOCUS_INPUT_START';
const RECEIVED_DATA_FOCUS_INPUT_START = 'RECEIVED_DATA_FOCUS_INPUT_START';
const FOCUS_INPUT_ARRIVED = 'FOCUS_INPUT_ARRIVED';
const RECEIVED_DATA_FOCUS_INPUT_ARRIVED = 'RECEIVED_DATA_FOCUS_INPUT_ARRIVED';

const GET_POPULAR_CITIES = 'GET_POPULAR_CITIES';
const RECEIVED_DATA_POPULAR_CITIES = 'RECEIVED_DATA_POPULAR_CITIES';

export default {
    UPDATE_INPUT_START_VALUE,
    ON_CHANGE_INPUT_START,
    RECEIVED_DATA_ON_CHANGE_INPUT_START,
    ON_CHANGE_INPUT_ARRIVED,
    RECEIVED_DATA_ON_CHANGE_INPUT_ARRIVED,
    FOCUS_INPUT_START,
    RECEIVED_DATA_FOCUS_INPUT_START,
    FOCUS_INPUT_ARRIVED,
    RECEIVED_DATA_FOCUS_INPUT_ARRIVED,
    GET_POPULAR_CITIES,
    RECEIVED_DATA_POPULAR_CITIES
}